name: Build & Attach Signed APK

on:
  release:
    types:
      - created

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js (v18)
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install npm dependencies
        run: npm ci

      - name: Install Expo CLI
        run: npm install --global expo-cli

      - name: Expo -> prebuild Android
        run: |
          expo prebuild --clean --platform android

      - name: Set up Java (Zulu JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Decode Android keystore from Secrets
        run: |
          mkdir -p android/app
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/app/release-key.jks
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Configure Gradle signing properties
        run: |
          cat <<EOF >> android/gradle.properties
          MYAPP_RELEASE_STORE_FILE=release-key.jks
          MYAPP_RELEASE_KEY_ALIAS=${ANDROID_KEY_ALIAS}
          MYAPP_RELEASE_STORE_PASSWORD=${ANDROID_KEYSTORE_PASSWORD}
          MYAPP_RELEASE_KEY_PASSWORD=${ANDROID_KEY_PASSWORD}
          EOF
        env:
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Build signed APK via Gradle
        run: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease

      - name: Verify APK signature
        run: |
          jarsigner -verify -verbose -certs android/app/build/outputs/apk/release/app-release.apk

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: android/app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
