name: Build and Release Signed APK

on:
  release:
    types: [created]

jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Generate Android project
        run: expo prebuild --clean --platform android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Prepare Android directory
        run: mkdir -p android/app

      - name: Install keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/elevator-app.jks

      - name: Configure signing
        run: |
          echo "MYAPP_RELEASE_STORE_FILE=elevator-app.jks" >> android/gradle.properties
          echo "MYAPP_RELEASE_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/gradle.properties
          echo "MYAPP_RELEASE_STORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/gradle.properties
          echo "MYAPP_RELEASE_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/gradle.properties

      - name: Build signed APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Verify APK signature
        run: |
          jarsigner -verify -verbose -certs android/app/build/outputs/apk/release/app-release.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: elevator-app-signed
          path: android/app/build/outputs/apk/release/app-release.apk

  attach-to-release:
    needs: build-android-apk
    runs-on: ubuntu-latest
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: elevator-app-signed
          path: dist

      - name: Attach APK to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
